#################################################
# Autmated setup of local environment
#################################################
---
- hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/default.yml

  roles:
    - role: dependencies
      tags:
        - setup
    - role: drivers
      tags:
        - drivers
    - role: gbitdev.fish



    #################################################
    # Setup fish shell
    #################################################

    # - name: Check if fisher is installed
    #   stat: path={{ home }}/.pow
    #   register: pow_installed

    # - name: Install Pow
    #   shell: curl get.pow.cx | sh
      # when: pow_installed.stat.exists == false
    # TODO: Get default shell setting to work
    # - name: Set "fish" as default shell
    #  command: chsh -s /usr/bin/fish
    #  tags:
    #    - default
